// Generated by https://quicktype.io

namespace SpotifyApi.NetCore
{
    using System.Text.Json.Serialization;
    using SpotifyApi.NetCore.Models;
    using System;

    /// <summary>
    /// Search Result.
    /// </summary>
    /// <remarks> https://developer.spotify.com/documentation/web-api/reference/search/search/ </remarks>
    public partial class SearchResult
    {
        [JsonPropertyName("artists")]
        public ArtistsSearchResult Artists { get; set; }

        [JsonPropertyName("albums")]
        public AlbumsSearchResult Albums { get; set; }

        [JsonPropertyName("tracks")]
        public TracksSearchResult Tracks { get; set; }

        [JsonPropertyName("playlists")]
        public PlaylistsSearchResult Playlists { get; set; }
    }

    /// <summary>
    /// Artists Search Result.
    /// </summary>
    public partial class ArtistsSearchResult : Paged<Artist>
    {
    }

    /// <summary>
    /// Albums Search Result.
    /// </summary>
    public partial class AlbumsSearchResult : Paged<Album>
    {
    }

    /// <summary>
    /// Tracks Search Result.
    /// </summary>
    public partial class TracksSearchResult : Paged<Track>
    {
    }

    /// <summary>
    /// Playlists Search Result
    /// </summary>
    public partial class PlaylistsSearchResult : Paged<PlaylistSimplified>
    {
    }
}
