// Generated by https://quicktype.io
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace SpotifyApi.NetCore
{
    ///<summary>
    /// Track Audio Analysis
    ///</summary>
    public partial class TrackAudioAnalysis
    {
        [JsonPropertyName("bars")]
        public Bar[] Bars { get; set; }

        [JsonPropertyName("beats")]
        public Bar[] Beats { get; set; }

        [JsonPropertyName("meta")]
        public Meta Meta { get; set; }

        [JsonPropertyName("sections")]
        public Dictionary<string, double>[] Sections { get; set; }

        [JsonPropertyName("segments")]
        public Segment[] Segments { get; set; }

        [JsonPropertyName("tatums")]
        public Bar[] Tatums { get; set; }

        [JsonPropertyName("track")]
        public AudioAnalysisTrack Track { get; set; }
    }

    ///<summary>
    /// Bar object
    ///</summary>
    public partial class Bar
    {
        [JsonPropertyName("start")]
        public double Start { get; set; }

        [JsonPropertyName("duration")]
        public double Duration { get; set; }

        [JsonPropertyName("confidence")]
        public double Confidence { get; set; }
    }

    ///<summary>
    /// Meta object
    ///</summary>
    public partial class Meta
    {
        [JsonPropertyName("analyzer_version")]
        public string AnalyzerVersion { get; set; }

        [JsonPropertyName("platform")]
        public string Platform { get; set; }

        [JsonPropertyName("detailed_status")]
        public string DetailedStatus { get; set; }

        [JsonPropertyName("status_code")]
        public long StatusCode { get; set; }

        [JsonPropertyName("timestamp")]
        public long Timestamp { get; set; }

        [JsonPropertyName("analysis_time")]
        public double AnalysisTime { get; set; }

        [JsonPropertyName("input_process")]
        public string InputProcess { get; set; }
    }

    ///<summary>
    /// Segment object
    ///</summary>
    public partial class Segment
    {
        [JsonPropertyName("start")]
        public double Start { get; set; }

        [JsonPropertyName("duration")]
        public double Duration { get; set; }

        [JsonPropertyName("confidence")]
        public double Confidence { get; set; }

        [JsonPropertyName("loudness_start")]
        public double LoudnessStart { get; set; }

        [JsonPropertyName("loudness_max_time")]
        public double LoudnessMaxTime { get; set; }

        [JsonPropertyName("loudness_max")]
        public double LoudnessMax { get; set; }

        [JsonPropertyName("loudness_end")]
        public long LoudnessEnd { get; set; }

        [JsonPropertyName("pitches")]
        public double[] Pitches { get; set; }

        [JsonPropertyName("timbre")]
        public double[] Timbre { get; set; }
    }

    ///<summary>
    /// Audio analysis
    ///</summary>
    public partial class AudioAnalysisTrack
    {
        [JsonPropertyName("duration")]
        public double Duration { get; set; }

        [JsonPropertyName("sample_md5")]
        public string SampleMd5 { get; set; }

        [JsonPropertyName("offset_seconds")]
        public long OffsetSeconds { get; set; }

        [JsonPropertyName("window_seconds")]
        public long WindowSeconds { get; set; }

        [JsonPropertyName("analysis_sample_rate")]
        public long AnalysisSampleRate { get; set; }

        [JsonPropertyName("analysis_channels")]
        public long AnalysisChannels { get; set; }

        [JsonPropertyName("end_of_fade_in")]
        public long EndOfFadeIn { get; set; }

        [JsonPropertyName("start_of_fade_out")]
        public double StartOfFadeOut { get; set; }

        [JsonPropertyName("loudness")]
        public double Loudness { get; set; }

        [JsonPropertyName("tempo")]
        public double Tempo { get; set; }

        [JsonPropertyName("tempo_confidence")]
        public double TempoConfidence { get; set; }

        [JsonPropertyName("time_signature")]
        public long TimeSignature { get; set; }

        [JsonPropertyName("time_signature_confidence")]
        public long TimeSignatureConfidence { get; set; }

        [JsonPropertyName("key")]
        public long Key { get; set; }

        [JsonPropertyName("key_confidence")]
        public double KeyConfidence { get; set; }

        [JsonPropertyName("mode")]
        public long Mode { get; set; }

        [JsonPropertyName("mode_confidence")]
        public double ModeConfidence { get; set; }

        [JsonPropertyName("codestring")]
        public string Codestring { get; set; }

        [JsonPropertyName("code_version")]
        public double CodeVersion { get; set; }

        [JsonPropertyName("echoprintstring")]
        public string Echoprintstring { get; set; }

        [JsonPropertyName("echoprint_version")]
        public double EchoprintVersion { get; set; }

        [JsonPropertyName("synchstring")]
        public string Synchstring { get; set; }

        [JsonPropertyName("synch_version")]
        public long SynchVersion { get; set; }

        [JsonPropertyName("rhythmstring")]
        public string Rhythmstring { get; set; }

        [JsonPropertyName("rhythm_version")]
        public long RhythmVersion { get; set; }
    }
}
